
FROM python:3.14.0a1-slim

# Set working directory
WORKDIR /app

# Copy project files into the container
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Set the PYTHONPATH to include the src directory
ENV PYTHONPATH=/app/src

# Run pytest as the entrypoint
ENTRYPOINT ["pytest", "/app/tests"]
